default_language_version:
    python: python3.11
repos:
    - hooks:
        - id: check-json
        - id: check-merge-conflict
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
          exclude: examples/
        - id: check-added-large-files
        - id: pretty-format-json
          args:
            - --autofix
        - id: detect-aws-credentials
        - id: detect-private-key
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    - hooks:
        - id: forbid-tabs
          exclude: binary|\.bin$|rego|\.rego$|go|\.go$
          exclude_types:
            - python
            - javascript
            - dtd
            - markdown
            - makefile
            - xml
      repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8 # v1.5.6
    - hooks:
        - id: shellcheck
      repo: https://github.com/shellcheck-py/shellcheck-py
      rev: 745eface02aef23e168a8afb6b5737818efbea95 # v0.11.0.1
    - hooks:
        - id: markdownlint
          exclude: src/testdata|testdata
      repo: https://github.com/igorshubovych/markdownlint-cli
      rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e # v0.48.0
    - hooks:
        - id: terraform-fmt
          language_version: python3.11
      repo: https://github.com/jameswoolfenden/pre-commit
      rev: 4997cf8b63896568143d5c6e820741214bc9f314 # v0.1.61
    - hooks:
        - id: golangci-lint
      repo: https://github.com/golangci/golangci-lint
      rev: c0d3ddc9cf3faa61a4e378e879ece580256d76e5 # v2.12.2
    - hooks:
        - id: checkov
          language_version: python3.11
          args:
            - -d
            - .
      repo: https://github.com/bridgecrewio/checkov
      rev: e52a901a3829d818d20c9b75e544845c8b756968 # 3.2.526
    - hooks:
        - id: ghat-go
          name: ghat
          entry: ghat swot -d . --continue-on-error true
          language: golang
          types:
            - yaml
          always_run: true
          description: upgrade action dependencies
        - id: ghat-go-sift
          name: sift
          entry: ghat sift -d .
          language: golang
          types:
            - yaml
          always_run: true
          description: upgrade action dependencies
      repo: local
    - hooks:
        - id: go-fmt
          name: go fmt
          entry: go fmt
          args:
            - ./...
          language: system
          pass_filenames: false
          types:
            - go
        - id: go-imports
          name: go imports
          entry: goimports
          args:
            - -w
          language: system
          types:
            - go
        - id: go-unit-tests
          name: go unit tests
          entry: go test
          args:
            - ./...
          language: system
          pass_filenames: false
          types:
            - go
        - id: go-mod-tidy
          name: go mod tidy
          entry: go mod tidy
          language: system
          pass_filenames: false
          types:
            - go
      repo: local
