---
# Build and run the Go binary from the repo
# REQUIRES: Go v1.16+ installed
- id: ghat-go
  name: ghat
  description: upgrade action dependencies
  language: golang
  entry: ghat swot -d .
  pass_filenames: false
  types: [ yaml ]

- id: ghat-go-sift
  name: sift
  description: upgrade precommit dependencies
  language: golang
  entry: ghat sift -d .
  pass_filenames: false
  types: [ yaml ]

# Build and run `ghat-docs` assuming it was installed manually
# or via package manager
# REQUIRES: ghat-docs to be installed and on the $PATH
- id: ghat-system
  name: ghat
  description: upgrade action dependencies
  language: system
  entry: ghat swot -d .
  pass_filenames: false
  types: [ yaml ]

- id: ghat-system-sift
  name: sift
  description: upgrade pre-commit dependencies
  language: system
  entry: ghat sift -d .
  pass_filenames: false
  types: [ yaml ]

# Builds and runs the Docker image from the repo
# REQUIRES: Docker installed
- id: ghat-docker
  name: ghat
  description: upgrade action dependencies (via Docker build)
  language: docker
  entry: ghat swot -d .
  pass_filenames: false
  types: [ yaml ]

- id: ghat-docker-sift
  name: sift
  description: upgrade pre-commit dependencies (via Docker build)
  language: docker
  entry: ghat sift -d .
  pass_filenames: false
  types: [ yaml ]
