default_language_version:
    python: python3.11
repos:
    - hooks:
        - id: check-json
        - id: check-merge-conflict
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
          exclude: examples/
        - id: check-added-large-files
        - id: pretty-format-json
          args:
            - --autofix
        - id: detect-aws-credentials
        - id: detect-private-key
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c
    - hooks:
        - id: forbid-tabs
          exclude: binary|\.bin$|rego|\.rego$|go|\.go$
          exclude_types:
            - python
            - javascript
            - dtd
            - markdown
            - makefile
            - xml
      repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8
    - hooks:
        - id: shellcheck
      repo: https://github.com/shellcheck-py/shellcheck-py
      rev: 745eface02aef23e168a8afb6b5737818efbea95
    - hooks:
        - id: markdownlint
          exclude: src/testdata|testdata
      repo: https://github.com/igorshubovych/markdownlint-cli
      rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e
    - hooks:
        - id: terraform-fmt
          language_version: python3.11
      repo: https://github.com/jameswoolfenden/pre-commit
      rev: ba5c36a3150a4184f9ee362a5cf11611ee9ae185
    - hooks:
        - id: golangci-lint
      repo: https://github.com/golangci/golangci-lint
      rev: 8f3b0c7ed018e57905fbd873c697e0b1ede605a5
    - hooks:
        - id: checkov
          language_version: python3.11
          args:
            - -d
            - .
      repo: https://github.com/bridgecrewio/checkov
      rev: 68c02db9f1fb66ac561e7deb068be23413ace6bb
    - hooks:
        - id: ghat-go
          name: ghat
          entry: ghat swot -d . --continue-on-error true
          language: golang
          types:
            - yaml
          always_run: true
          description: upgrade action dependencies
        - id: ghat-go-sift
          name: sift
          entry: ghat sift -d .
          language: golang
          types:
            - yaml
          always_run: true
          description: upgrade action dependencies
      repo: local
    - hooks:
        - id: go-fmt
        - id: go-imports
        - id: go-unit-tests
          args:
            - ./...
        - id: go-mod-tidy
        - id: go-generate
        - id: validate-toml
        - id: no-go-testing
      repo: https://github.com/dnephin/pre-commit-golang
      rev: fb24a639f7c938759fe56eeebbb7713b69d60494
