---
# Build and run the Go binary from the repo
# REQUIRES: Go v1.16+ installed
- id: ghat-docs-go
  name: ghat-docs
  description: Generate Policy documentation for Terraform modules (via Go binary)
  language: golang
  entry: ghat
  pass_filenames: false
  types: [ terraform ]

# Build and run `ghat-docs` assuming it was installed manually
# or via package manager
# REQUIRES: ghat-docs to be installed and on the $PATH
- id: ghat-docs-system
  name: ghat-docs
  description: Generate Policy documentation for Terraform modules (via locally-installed CLI)
  language: system
  entry: ghat
  pass_filenames: false
  types: [ terraform ]

# Builds and runs the Docker image from the repo
# REQUIRES: Docker installed
- id: ghat-docs-docker
  name: ghat-docs
  description: Generate Policy documentation for Terraform modules (via Docker build)
  language: docker
  entry: ghat
  pass_filenames: false
  types: [ terraform ]
