requires 'Text::Template';
requires "JSON", '>= 2.00';

on 'test' => sub {
    requires 'Test::More', '0.96';
    requires 'Capture::Tiny'; # ghat:suppress:reason=core module proxy
};

recommends 'JSON::XS';
requires 'Already::Pinned', '== 1.23'; # left alone
requires 'Dist::From::Git', git => 'https://example.com/foo.git';
