on:
  pull_request_target:
    types: [opened]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        env:
          TOKEN: ${{ secrets.SOME_TOKEN }}
      - run: echo "${{ github.event.pull_request.title }}"
      - uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
  call:
    uses: owner/repo/.github/workflows/reusable.yml@main
