source 'https://rubygems.org'

gem 'rails', '~> 7.1'
gem 'pg', '>= 1.1'
gem 'puma', '>= 5.0'
gem 'bootsnap', require: false

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails'
end
