on: pull_request
name: Pull request
permissions: read-all
env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  lint:
    env:
      GOTOOLCHAIN: auto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: gofumpt
        env:
          GOTOOLCHAIN: auto
        uses: jameswoolfenden/auto-gofmt@658e0ca3f44450eb0229a26371b1432db51059a7 # v0.4.0
  test:
    env:
      GOTOOLCHAIN: auto
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -coverprofile=./cover.out
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run action from local checkout
        uses: ./
        with:
          verb: swot
          directory: .github/workflows
      - name: Assert workflows already pinned
        run: git diff --exit-code .github/workflows
